UPDATE `battleground_template` SET `MinPlayersPerTeam`='5' WHERE (`id`='1')
UPDATE `battleground_template` SET `MinPlayersPerTeam`='5' WHERE (`id`='3')
UPDATE `battleground_template` SET `MinPlayersPerTeam`='5' WHERE (`id`='7')
UPDATE `battleground_template` SET `MinPlayersPerTeam`='5' WHERE (`id`='9')
UPDATE `battleground_template` SET `MinPlayersPerTeam`='5' WHERE (`id`='30')
UPDATE `battleground_template` SET `MinPlayersPerTeam`='5' WHERE (`id`='32')
UPDATE `battleground_template` SET `MinPlayersPerTeam`='5' WHERE (`id`='108')